### ISSUE TITLE
Fazer o botão cadastre-se na tela inicial e o HTML de cadastro de usuários correspondente

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/slab#126]

**Comment by Emanuel331** [comment]
Enviado como cadastro.html

**Comment by Ronneesley** [comment]
Posicionar o botão cadastre-se em local adequado na tela.
Fazer esse botão ou link, cadastre-se, chamar a URL para essa finalidade: ``index.php?controle=usuario&acao=cadastre_se``
No formulário de cadastro colocar os rótulos nos campos além do `placeholder`. 
Adicionar campo de verificação de senha.

**Comment by Ronneesley** [comment]
Nova issue aberta para atividade correlata #127

**Comment by Ronneesley** [comment]
Arquivo renomeado para `cadastre_se.html` no próximo commit que farei.

**Comment by Emanuel331** [comment]
Feito

**Comment by Ronneesley** [comment]
![image](https://user-images.githubusercontent.com/29005089/208915632-b0b1db94-48ac-4100-8258-04ff5a04298f.png)

Que tal mover esse botão para a parte de cima e deixá-lo parecido com o botão "Entrar"?

Uma outra opção é colocar essa ação como um link assim como o "Esqueceu a senha".

Aguardo uma destas edição, veja qual fica melhor.

**Comment by orlandofilho04** [comment]
Todas as alterações feitas. Funcioanando.
