### ISSUE TITLE
Validar o preenchimento do formulário de cadastre-se com JavaScript

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/slab#127]
Fazer um código JavaScript que valide os campos do formulário de cadastre-se: `index.php?controle=usuario&acao=cadastre_se`.

1. Validar se nome, email e senha foram preenchidos.
2. Validar se o E-mail é válido
3. Validar se a senha é igual à confirmação de senha

**Comment by orlandofilho04** [comment]
Funcionalidades incrementadas. Ao tentar cadastrar-se, as senhas do campo senha e do campo confirmar senha precisam ser obrigatoriamente iguais, caso contrário o cadastro não é efetuado, junto com a validação da estrutura de um email, se não seguir estrutura "exemplo@exemplo@exp" não deixa cadastrar e contém restrição de que todos os campos sejam obrigatórios, caso contrário o formulário nem é enviado. Tudo funcioanando.
